#!/bin/bash
#
# Copyright [2013-2014] eBay Software Foundation
#  
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#  
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# friendly message for those who forget to tell us what to do
if [ $# = 0 ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "h" ] || [ "$1" == "help" ] ; then
  echo "Usage: guagua [-y(enable beta guagua-yarn version on hadoop 2.0)] jar <the jar containing master and worker class> [-D<hadoop/guagua property>] <parameters to jar>"
  exit 1
fi

# locate and run the guagua-env script to populate env vars, classpath, etc.
GUAGUA_ENV_DIR="$( cd -P "$( dirname "${BASH_SOURCE:-0}" )" && pwd )"
source $GUAGUA_ENV_DIR/guagua-env

exec "$HADOOP_ROOT/bin/hadoop" jar $JAR $CLASS -libjars $GUAGUA_JARS "$@" $HADOOP_PROPERTIES

