#!/bin/bash
#
# Copyright [2013-2014] PayPal Software Foundation
#  
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#  
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The Guagua command script
#
# Environment Variables
#
#   GUAGUA_OPTS         Extra Java runtime options.
#
#   GUAGUA_CLASSPATH    Extra Java CLASSPATH entries.
#
#   GUAGUA_CONF_DIR     Guagua conf folder, default is in GUAUGA_HOME/conf

# locate and run the guagua-env script to populate env vars, classpath, etc.
GUAGUA_ENV_DIR="$( cd -P "$( dirname "${BASH_SOURCE:-0}" )" && pwd )"

# print version string
if  [ "$1" == "-v" ] || [ "$1" == "-version" ] || [ "$1" == "v" ] || [ "$1" == "version" ] ; then
    client_jar=`ls -al ${GUAGUA_ENV_DIR}/../common-lib | grep guagua-client | awk '{print $NF}'`
    java -jar ${GUAGUA_ENV_DIR}/../common-lib/${client_jar} v
    exit 0
fi

# friendly message for those who forget to tell us what to do
if [ $# = 0 ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "h" ] || [ "$1" == "help" ] ; then
    client_jar=`ls -al ${GUAGUA_ENV_DIR}/../common-lib | grep guagua-client | awk '{print $NF}'`
    java -jar ${GUAGUA_ENV_DIR}/../common-lib/${client_jar} h
    exit 1
fi

source $GUAGUA_ENV_DIR/guagua-env

exec "$HADOOP_ROOT/bin/hadoop" jar $JAR $CLASS -libjars $GUAGUA_JARS "$@" $HADOOP_PROPERTIES

